# Generated by Django 2.1.1 on 2018-10-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_Name', models.CharField(max_length=250)),
                ('Description', models.CharField(max_length=400)),
                ('item', models.CharField(max_length=450)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Partener_company', models.CharField(max_length=250)),
                ('Associted_person', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=270)),
                ('Phone_number', models.CharField(max_length=270)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=250)),
            ],
        ),
    ]
